# Generated by Django 5.1.2 on 2025-05-05 21:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto'), ('home', 'Home'), ('life', 'Life'), ('health', 'Health')], max_length=20)),
                ('expiry_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 5))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
